# Dependabot will run on day 14 of each month at 01:13 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "13 1 14 * *"
    open-pull-requests-limit: 15

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "13 1 14 * *"
    open-pull-requests-limit: 20
    assignees:
      - "Excodibur"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "production"
